language: rust

rust:
  # Test every other release since the minimum supported version to not waste
  # too many resources.
  - 1.8.0
  - 1.10.0
  - 1.12.0
  - 1.14.0
  - 1.16.0
  - 1.18.0
  - beta
  - nightly
